### ISSUE TITLE
how to change pins in macros and what to replace

### ISSUE THREAD

**Issue by anoopsingh2906** [Cooble/Pulser#1]
hello, friend i really thank you for this great library can you please tell me how to use it because you have written everywhere just replace pins and pin mode , haven't told that what should we write there and whats the format for declaring pins , even am unable to run your only example that is  showing me error in compiling ,waiting for your reply

**Comment by Cooble** [comment]
Hi,
I am incredibly sorry for not responding sooner. Not sure whether it is worth anything now but I added second example that shows in the comment section how to modify Pulser.h to change default pin. For completion here is [port manipulation tutorial](https://www.arduino.cc/en/Reference/PortManipulation) which describes how to switch pins directly using registers.
